controller_manager:
  ros__parameters:
    update_rate: 70  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

forward_voltage_controller:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    joints:
      - chassis_fr_wheel_joint
      - chassis_fl_wheel_joint
      - chassis_rl_wheel_joint
      - chassis_rr_wheel_joint
    interface_name: voltage

jacobian:
  ros__parameters:
    type: mecanum_jacobian/JacobianController
    joints:
      - chassis_fr_wheel_joint
      - chassis_fl_wheel_joint
      - chassis_rl_wheel_joint
      - chassis_rr_wheel_joint

inverse_jacobian:
  ros__parameters:
    type: mecanum_jacobian/InverseJacobianController
    joints:
      - chassis_fr_wheel_joint
      - chassis_fl_wheel_joint
      - chassis_rl_wheel_joint
      - chassis_rr_wheel_joint